name: CI/CD

on:
  push:
    branches:
      - ci_cd_issue_85

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'  

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm test

  deploy:
    needs: build  

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm test

      - name: Deploy frontend
        run: |
          npm install -g http-server
          http-server -c-1 -a 0.0.0.0 -p 8080 &

      - uses: luisboto/ngrok-tunnel-action@0.1.7.2
        with:
          timeout: 1h
          port: 8080
          ngrok_authtoken: 1RKuzeUZrXfSKFhJ5mvbwxwRmhQ_48TNmwv1j3wxX97GzFrg3
          tunnel_type: http
      #- name: Deploy backend

       
